export type InvoiceLocale = "zh" | "en";

const zhInvoicePageCopy = {
  header: {
    title: "健身房发票与报价管理",
    subtitle: "Gym Invoice & Quotation Management",
    tagline: "高效管理，财务无忧",
    backToList: "返回发票列表",
    actions: "操作菜单",
    createInvoice: "生成新发票",
    templateSettings: "模板设置",
  },
  feedback: {
    saveInvoiceRequired: "请先完整填写客户信息与发票项目，再保存。",
    paymentRequired: "请先选择付款方式。",
    invoiceSaved: "发票已成功保存到数据库。",
    saveFailed: "保存失败，请稍后重试",
    templateLoadFailed: "模板设置加载失败",
    templateSaveFailed: "模板设置保存失败",
    templateSaved: "模板设置已保存",
    noTemplatePermission: "你没有管理员权限，无法修改模板设置。",
    deleteFailed: "删除失败，请稍后重试",
    customerSaveFailed: "保存失败，请稍后重试",
  },
  modal: {
    cancel: "取消",
    close: "关闭",
    confirm: "确认",
    customerInfo: {
      title: "添加客户信息",
      description: "用于发票抬头、发送与结算记录",
      name: "客户姓名",
      namePlaceholder: "请输入客户姓名",
      email: "邮箱",
      emailPlaceholder: "请输入邮箱",
      streetAddress: "街道地址",
      streetAddressPlaceholder: "请输入街道地址",
      city: "城市",
      cityPlaceholder: "例如 Toronto",
      province: "省",
      postcode: "Postcode",
      postcodePlaceholder: "A1A 1A1",
      country: "国家",
      save: "保存客户信息",
    },
    itemPicker: {
      title: "选择可添加项目",
      searchPlaceholder: "搜索项目（如：私教、周期、储值）",
      loading: "正在加载项目...",
      noItems: "暂无可选项目，请检查数据库配置。",
      noMatch: "未找到匹配项目，请尝试其他关键词。",
      noSectionItems: "暂无项目",
      pricePending: "价格待定",
      sections: {
        membership: "会员团课",
        group_class: "团课课程",
        personal_training: "私教课程",
        cycle_plan: "周期计划",
        stored_value: "储值计划",
      },
    },
    customerDb: {
      title: "从数据库选择客户",
      searchPlaceholder: "筛选客户（姓名 / 邮箱 / 地址）",
      noMatch: "没有匹配的客户",
    },
    confirmDelete: {
      title: "删除发票",
      description: (invoiceNo: string) => `确定要删除发票 ${invoiceNo} 吗？此操作不可恢复。`,
      confirmLabel: "确认删除",
      deleting: "删除中...",
    },
    customerProfile: {
      titleCreate: "创建新客户",
      titleEdit: "编辑客户档案",
      saveCreate: "保存客户档案",
      saveEdit: "保存修改",
      saving: "保存中...",
    },
    invoicePreview: {
      titlePrefix: "发票详情 · ",
      downloadPdf: "下载 PDF",
    },
  },
  template: {
    title: "模板设置",
    loading: "模板设置加载中...",
    closeAria: "关闭模板设置",
    brandColor: "品牌色",
    sectionHint: "按模块维护模板信息，右侧区域独立滚动，支持后续继续扩展字段。",
    footerHint: "修改仅影响模板样式与 Oxygen 固定信息。",
    resetDefault: "重置默认",
    saving: "保存中...",
    save: "保存模板",
    previewFallbackCompany: "Oxygen",
    previewFallbackSubtitle: "Invoice template",
    groups: {
      header: "抬头与编号",
      company: "公司信息",
      terms: "条款与备注",
    },
    fieldLabels: {
      invoiceTitle: "Invoice 标题",
      headerSubtitle: "顶部副标题",
      dateLabel: "日期标签",
      invoiceNoLabel: "发票编号标签",
      hstLabel: "HST 标签",
      hstNumber: "HST 号码",
      fromTitle: "From 标题",
      billToTitle: "Bill To 标题",
      companyName: "公司名称",
      addressLine1: "地址第 1 行",
      addressLine2: "地址第 2 行",
      country: "国家",
      email: "联系邮箱",
      paymentTermsTitle: "付款条款标题",
      notesTitle: "备注标题",
      notesTemplate: "备注模板（支持 {{paymentMethod}}）",
      termsTitle: "条款标题",
      termsDescription: "条款说明",
      thankYouMessage: "感谢语",
    },
  },
  document: {
    paymentPending: "待支付",
    newCustomerDraft: "新客户（草稿）",
    streetPending: "街道地址待填写",
    cityProvincePostcodePending: "城市 / 省 / 邮编待填写",
    countryPending: "国家待填写",
    emailPending: "邮箱待填写",
    table: {
      description: "项目描述",
      quantity: "数量",
      unitPrice: "单价",
      discount: "折扣",
      total: "总计",
      untitledItem: "未命名项目",
    },
    tbd: "待定",
    summary: {
      subtotal: "小计",
      tax: "税费",
      total: "总额",
    },
  },
  builder: {
    customerInfoTitle: "客户信息",
    pickCustomerFromDb: "从客户档案选择",
    createCustomerProfile: "新建客户档案",
    quoteBuilderTitle: "交互式报价构建器",
    emptyItemsTitle: "当前还没有项目",
    emptyItemsHint: "请先从数据库选择项目，或添加一个自定义空白项目",
    labels: {
      itemName: "项目名称 (Manual Entry)",
      qty: "数量",
      unitPrice: "单价 ($)",
      discount: "Discount ($)",
      nonTaxable: "非税项目",
    },
    addFromDb: "添加新的项目（从数据库选择）",
    addCustom: "自定义添加空白项目",
    totalAmount: "合计金额",
    taxHint: "包含 13% 税费（储值项目不计税）",
    totalItems: "项目总数",
    itemsSuffix: "项",
    paymentMethod: "付款方式",
    customPaymentPlaceholder: "输入自定义付款方式",
    save: "保存发票",
    saving: "保存中...",
    livePreview: "实时发票预览",
    downloadPdf: "下载 PDF",
  },
  table: {
    tabs: {
      invoiceList: "发票列表",
      quotationList: "报价列表",
      customerList: "客户档案",
      imageUpload: "上传图片",
    },
    management: {
      invoice: "发票管理",
      quotation: "报价管理",
      customer: "客户档案",
      images: "图片上传",
      realtime: "实时筛选",
    },
    searchPlaceholder: {
      invoice: "搜索发票编号 / 客户 / 状态",
      quotation: "搜索报价单 / 客户 / 方案",
      customer: "搜索客户姓名 / 联系方式",
      images: "搜索图片文件名",
    },
    quotation: {
      create: "创建新报价单",
      noMatch: "未找到匹配报价单。",
    },
    invoice: {
      all: "所有发票",
      loadingCustomers: "正在加载客户档案...",
      duplicateWarning: (count: number, emails: string) => `检测到重复客户邮箱（${count}）: ${emails}。建议合并重复档案，避免编辑误操作。`,
      headers: {
        invoiceNo: "发票编号",
        customerName: "客户名称",
        total: "总金额",
        date: "结算日期",
        status: "状态",
        action: "操作",
      },
      statusFilter: {
        all: "全部",
        sent: "已发送",
        notSent: "未发送",
      },
      empty: "暂时没有发票数据",
      showing: (count: number) => `显示 ${count} 条记录`,
      resetFilter: "重置筛选",
    },
    customer: {
      overview: "客户档案总览",
      add: "添加客户档案",
      headers: {
        customer: "客户",
        contact: "联系方式",
        totalAmount: "累计金额",
        latest: "最近交易",
        action: "操作",
      },
      edit: "编辑",
      empty: "未找到匹配客户。",
    },
  },
} as const;

/**
 * Same keys/shape as zh copy, but string literals are widened to `string` so en (and future locales)
 * are not forced to match Chinese wording character-for-character.
 */
type Widened<T> = T extends (...args: infer A) => infer R
  ? (...args: A) => Widened<R>
  : T extends ReadonlyArray<infer U>
    ? Array<Widened<U>>
    : T extends object
      ? { [K in keyof T]: Widened<T[K]> }
      : T extends string
        ? string
        : T;

type InvoicePageCopySchema = Widened<typeof zhInvoicePageCopy>;

const enInvoicePageCopy: InvoicePageCopySchema = {
  header: {
    title: "Gym Invoice & Quotation Management",
    subtitle: "Fast management, stress-free finance",
    tagline: "Accurate billing, efficient workflow",
    backToList: "Back to invoice list",
    actions: "Actions",
    createInvoice: "Create New Invoice",
    templateSettings: "Template Settings",
  },
  feedback: {
    saveInvoiceRequired: "Please complete customer info and invoice items before saving.",
    paymentRequired: "Please select a payment method first.",
    invoiceSaved: "Invoice has been saved to database.",
    saveFailed: "Save failed, please try again later",
    templateLoadFailed: "Failed to load template settings",
    templateSaveFailed: "Failed to save template settings",
    templateSaved: "Template settings saved",
    noTemplatePermission: "You don't have admin permission to modify template settings.",
    deleteFailed: "Delete failed, please try again later",
    customerSaveFailed: "Save failed, please try again later",
  },
  modal: {
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    customerInfo: {
      title: "Add Customer Information",
      description: "Used for invoice heading, delivery and settlement records",
      name: "Customer Name",
      namePlaceholder: "Enter customer name",
      email: "Email",
      emailPlaceholder: "Enter email",
      streetAddress: "Street Address",
      streetAddressPlaceholder: "Enter street address",
      city: "City",
      cityPlaceholder: "e.g. Toronto",
      province: "Province",
      postcode: "Postcode",
      postcodePlaceholder: "A1A 1A1",
      country: "Country",
      save: "Save Customer Info",
    },
    itemPicker: {
      title: "Select Items to Add",
      searchPlaceholder: "Search items (e.g. PT, cycle, stored value)",
      loading: "Loading items...",
      noItems: "No items available. Please check database configuration.",
      noMatch: "No matching items. Try another keyword.",
      noSectionItems: "No items",
      pricePending: "Price pending",
      sections: {
        membership: "Membership",
        group_class: "Group Class",
        personal_training: "Personal Training",
        cycle_plan: "Cycle Plan",
        stored_value: "Stored Value",
      },
    },
    customerDb: {
      title: "Select Customer from Database",
      searchPlaceholder: "Filter customers (name / email / address)",
      noMatch: "No matching customers",
    },
    confirmDelete: {
      title: "Delete Invoice",
      description: (invoiceNo: string) => `Are you sure you want to delete invoice ${invoiceNo}? This action cannot be undone.`,
      confirmLabel: "Delete",
      deleting: "Deleting...",
    },
    customerProfile: {
      titleCreate: "Create New Customer",
      titleEdit: "Edit Customer Profile",
      saveCreate: "Save Customer Profile",
      saveEdit: "Save Changes",
      saving: "Saving...",
    },
    invoicePreview: {
      titlePrefix: "Invoice Details · ",
      downloadPdf: "Download PDF",
    },
  },
  template: {
    title: "Template Settings",
    loading: "Loading template settings...",
    closeAria: "Close template settings",
    brandColor: "Brand color",
    sectionHint: "Manage template content by module. Right panel scrolls independently for scalability.",
    footerHint: "Changes only affect template styling and Oxygen static info.",
    resetDefault: "Reset Default",
    saving: "Saving...",
    save: "Save Template",
    previewFallbackCompany: "Oxygen",
    previewFallbackSubtitle: "Invoice template",
    groups: {
      header: "Header & Numbering",
      company: "Company Info",
      terms: "Terms & Notes",
    },
    fieldLabels: {
      invoiceTitle: "Invoice title",
      headerSubtitle: "Header subtitle",
      dateLabel: "Date label",
      invoiceNoLabel: "Invoice no label",
      hstLabel: "HST label",
      hstNumber: "HST number",
      fromTitle: "From title",
      billToTitle: "Bill to title",
      companyName: "Company name",
      addressLine1: "Address line 1",
      addressLine2: "Address line 2",
      country: "Country",
      email: "Email",
      paymentTermsTitle: "Payment terms title",
      notesTitle: "Notes title",
      notesTemplate: "Notes template (supports {{paymentMethod}})",
      termsTitle: "Terms title",
      termsDescription: "Terms description",
      thankYouMessage: "Thank you message",
    },
  },
  document: {
    paymentPending: "Payment pending",
    newCustomerDraft: "New Customer (Draft)",
    streetPending: "Street address pending",
    cityProvincePostcodePending: "City / Province / Postcode pending",
    countryPending: "Country pending",
    emailPending: "Email pending",
    table: {
      description: "Description",
      quantity: "Quantity",
      unitPrice: "Unit Price",
      discount: "Discount",
      total: "Total",
      untitledItem: "Untitled Item",
    },
    tbd: "TBD",
    summary: {
      subtotal: "Subtotal",
      tax: "Tax",
      total: "Total",
    },
  },
  builder: {
    customerInfoTitle: "Customer Information",
    pickCustomerFromDb: "Pick from customer profiles",
    createCustomerProfile: "Create customer profile",
    quoteBuilderTitle: "Interactive Quote Builder",
    emptyItemsTitle: "No items yet",
    emptyItemsHint: "Pick items from database or add a blank custom item first",
    labels: {
      itemName: "Item Name (Manual Entry)",
      qty: "Qty",
      unitPrice: "Unit Price ($)",
      discount: "Discount ($)",
      nonTaxable: "Non-taxable",
    },
    addFromDb: "Add item (from database)",
    addCustom: "Add blank custom item",
    totalAmount: "Total Amount",
    taxHint: "Includes 13% tax (stored value excluded)",
    totalItems: "Total Items",
    itemsSuffix: "items",
    paymentMethod: "Payment Method",
    customPaymentPlaceholder: "Enter custom payment method",
    save: "Save Invoice",
    saving: "Saving...",
    livePreview: "Live Invoice Preview",
    downloadPdf: "Download PDF",
  },
  table: {
    tabs: {
      invoiceList: "Invoice List",
      quotationList: "Quotation List",
      customerList: "Customer Profiles",
      imageUpload: "Upload Images",
    },
    management: {
      invoice: "Invoice Management",
      quotation: "Quotation Management",
      customer: "Customer Profiles",
      images: "Image Upload",
      realtime: "Realtime Filter",
    },
    searchPlaceholder: {
      invoice: "Search invoice no / customer / status",
      quotation: "Search quotation / customer / plan",
      customer: "Search customer name / contact",
      images: "Search image file name",
    },
    quotation: {
      create: "Create New Quotation",
      noMatch: "No matching quotations found.",
    },
    invoice: {
      all: "All Invoices",
      loadingCustomers: "Loading customer profiles...",
      duplicateWarning: (count: number, emails: string) => `Detected duplicate customer emails (${count}): ${emails}. Consider merging profiles to avoid editing mistakes.`,
      headers: {
        invoiceNo: "Invoice No",
        customerName: "Customer",
        total: "Total",
        date: "Settlement Date",
        status: "Status",
        action: "Actions",
      },
      statusFilter: {
        all: "All",
        sent: "Sent",
        notSent: "Not Sent",
      },
      empty: "No invoices yet",
      showing: (count: number) => `showing ${count} records`,
      resetFilter: "Reset Filters",
    },
    customer: {
      overview: "Customer Profile Overview",
      add: "Add Customer Profile",
      headers: {
        customer: "Customer",
        contact: "Contact",
        totalAmount: "Total Amount",
        latest: "Latest Transaction",
        action: "Actions",
      },
      edit: "Edit",
      empty: "No matching customers found.",
    },
  },
};

export const invoicePageCopy: Record<InvoiceLocale, InvoicePageCopySchema> = {
  zh: zhInvoicePageCopy,
  en: enInvoicePageCopy,
};

export function getInvoicePageCopy(locale: InvoiceLocale) {
  return invoicePageCopy[locale];
}
