export const cycleCopy = {
  zh: {
    cycleProgram: "周期方案",
    weeklySessions: "每周次数",
    minSessions: "最少课时",
    followups: "跟进次数",
    assessments: "评估报告",
    membershipGift: "赠送会籍",
    extraBenefits: "额外权益",
    ptProgram: "私教课程",
    pricingBreakdown: "价格明细",
    item: "项目",
    unit: "单价",
    qty: "数量",
    subtotal: "小计",
    cyclePlan: "周期计划",
    credit: "积分抵扣",
    afterCredit: "抵扣后金额",
    tax: "税费",
    total: "总计",
    back: "返回",
    close: "关闭",
    selectProgram: "选择私教课程 · 按价格升序",
    programColumn: "课程",
    member: "会员",
    nonMember: "非会员",
    defaultSessions: "默认 12 课时",
    clientName: "客户姓名",
    clientPlaceholder: "请输入客户姓名",
    unitPrice: "单价",
    quantity: "数量",
    sessions: "课时",
    activePlan: "当前方案",
    next: "下一步",
    copySummary: "复制报告摘要",
    copied: "已复制",
    copiedHint: "已复制到剪贴板",
    downloadPdf: "下载 PDF",
    noPrograms: "暂无可选私教课程，请先在数据中配置私教课程。",
    step1: "选私教课程",
    step2: "算价格明细",
    step3: "生成完整报告",
    selectedProgram: "已选私教课程",
    planInputs: "方案与参数",
    member1v1: "会员 1v1",
    nonMember1v1: "非会员 1v1",
    member1v2: "会员 1v2",
    nonMember1v2: "非会员 1v2",
  },
  en: {
    cycleProgram: "Cycle Program",
    weeklySessions: "Weekly Sessions",
    minSessions: "Min Sessions",
    followups: "Followups",
    assessments: "Assessments",
    membershipGift: "Membership Gift",
    extraBenefits: "Extra Benefits",
    ptProgram: "PT Program",
    pricingBreakdown: "Pricing Breakdown",
    item: "Item",
    unit: "Unit",
    qty: "Qty",
    subtotal: "Subtotal",
    cyclePlan: "Cycle Plan",
    credit: "Credit",
    afterCredit: "After Credit",
    tax: "Tax",
    total: "Total",
    back: "Back",
    close: "Close",
    selectProgram: "Select PT Program · Price low to high",
    programColumn: "Program",
    member: "Member",
    nonMember: "Non-mbr",
    defaultSessions: "Default 12 sessions",
    clientName: "Client Name",
    clientPlaceholder: "Enter client name",
    unitPrice: "Unit Price",
    quantity: "Quantity",
    sessions: "sessions",
    activePlan: "Active Plan",
    next: "Next",
    copySummary: "Copy Summary",
    copied: "Copied",
    copiedHint: "Copied to clipboard",
    downloadPdf: "Download PDF",
    noPrograms: "No PT programs available. Please configure Personal Training first.",
    step1: "Select PT Program",
    step2: "Pricing Breakdown",
    step3: "Generate Report",
    selectedProgram: "Selected PT Program",
    planInputs: "Plan & Inputs",
    member1v1: "Member 1v1",
    nonMember1v1: "Non-member 1v1",
    member1v2: "Member 1v2",
    nonMember1v2: "Non-member 1v2",
  },
};
