export const ptCalculatorCopy = {
  zh: {
    stepTitle: "步骤 2 · 课程价格计算",
    planInputs: "方案与参数",
    member1v1: "会员 1v1",
    nonMember1v1: "非会员 1v1",
    member1v2: "会员 1v2",
    nonMember1v2: "非会员 1v2",
    defaultSessions: "默认 12 课时",
    unitPrice: "单价",
    sessions: "课时",
    planSummary: "方案汇总",
    activePlan: "当前方案",
    subtotal: "小计",
    credit: "积分抵扣",
    afterCredit: "抵扣后金额",
    tax: "税费",
    total: "总计",
    generateReport: "生成报告单",
    quoteNote: "价格仅供销售演示，最终以合同为准。",
    assessmentFocus: "专项评估与指标解读",
    assessmentIdealFor: "首次建档、复测追踪客户",
  },
  en: {
    stepTitle: "Step 2 · Course Pricing Calculator",
    planInputs: "Plan & Inputs",
    member1v1: "Member 1v1",
    nonMember1v1: "Non-member 1v1",
    member1v2: "Member 1v2",
    nonMember1v2: "Non-member 1v2",
    defaultSessions: "Default 12 sessions",
    unitPrice: "Unit Price",
    sessions: "sessions",
    planSummary: "Plan Summary",
    activePlan: "Active Plan",
    subtotal: "Subtotal",
    credit: "Credit",
    afterCredit: "After Credit",
    tax: "Tax",
    total: "Total",
    generateReport: "Generate Report",
    quoteNote: "For quotation preview only.",
    assessmentFocus: "Assessment insights and metrics review",
    assessmentIdealFor: "First-time and follow-up clients",
  },
};

export const ptReportCopy = {
  zh: {
    title: "报告单",
    close: "关闭",
    date: "日期",
    clientName: "客户姓名",
    clientPlaceholder: "请输入客户姓名",
    itemDetails: "项目明细",
    item: "项目",
    unit: "单价",
    qty: "数量",
    subtotal: "小计",
    member1v1: "1v1 会员",
    nonMember1v1: "1v1 非会员",
    member1v2: "1v2 会员",
    nonMember1v2: "1v2 非会员",
    activePlan: "当前方案",
    credit: "积分抵扣",
    afterCredit: "抵扣后金额",
    tax: "税费",
    total: "总计",
    copied: "已复制",
    copySummary: "复制项目摘要",
    downloadPdf: "下载 PDF",
  },
  en: {
    title: "Quotation Report",
    close: "Close",
    date: "Date",
    clientName: "Client Name",
    clientPlaceholder: "Enter client name",
    itemDetails: "Item Details",
    item: "Item",
    unit: "Unit",
    qty: "Qty",
    subtotal: "Subtotal",
    member1v1: "1v1 Member",
    nonMember1v1: "1v1 Non-member",
    member1v2: "1v2 Member",
    nonMember1v2: "1v2 Non-member",
    activePlan: "Active Plan",
    credit: "Credit",
    afterCredit: "After Credit",
    tax: "Tax",
    total: "Total",
    copied: "Copied",
    copySummary: "Copy Item Summary",
    downloadPdf: "Download PDF",
  },
};
